# Generated by Django 5.2.15 on 2026-07-03 21:33

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EmailLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("recipient", models.EmailField(db_index=True, max_length=254)),
                ("subject", models.CharField(max_length=512)),
                ("template", models.CharField(blank=True, max_length=255)),
                ("purpose", models.CharField(blank=True, db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("sent", "Sent"),
                            ("delivered", "Delivered"),
                            ("bounced", "Bounced"),
                            ("deferred", "Deferred"),
                            ("complained", "Complained"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="pending",
                        max_length=16,
                    ),
                ),
                (
                    "provider_message_id",
                    models.CharField(blank=True, db_index=True, max_length=255),
                ),
                ("error", models.TextField(blank=True)),
                ("related_object_type", models.CharField(blank=True, max_length=64)),
                (
                    "related_object_id",
                    models.CharField(blank=True, db_index=True, max_length=64),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                ("delivered_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "email_log",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["recipient", "-created_at"],
                        name="email_log_recipie_6dfd0b_idx",
                    ),
                    models.Index(
                        fields=["purpose", "-created_at"],
                        name="email_log_purpose_fcb82d_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sent_at__isnull", True),
                            ("created_at__isnull", True),
                            ("sent_at__gte", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="emaillog_sent_after_created",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("delivered_at__isnull", True),
                            ("sent_at__isnull", True),
                            ("delivered_at__gte", models.F("sent_at")),
                            _connector="OR",
                        ),
                        name="emaillog_delivered_after_sent",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="BackgroundJob",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("kind", models.CharField(db_index=True, max_length=64)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("running", "Running"),
                            ("done", "Done"),
                            ("failed", "Failed"),
                        ],
                        db_index=True,
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("progress", models.JSONField(blank=True, default=dict)),
                ("result", models.JSONField(blank=True, default=dict)),
                ("error", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("heartbeat_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="background_jobs_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "background_job",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["kind", "-created_at"],
                        name="background__kind_aa9881_idx",
                    ),
                    models.Index(
                        fields=["status", "-created_at"],
                        name="background__status_33fa66_idx",
                    ),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("completed_at__isnull", True),
                            ("created_at__isnull", True),
                            ("completed_at__gte", models.F("created_at")),
                            _connector="OR",
                        ),
                        name="backgroundjob_completed_after_created",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="EmailTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("slug", models.CharField(max_length=64)),
                ("language", models.CharField(default="en", max_length=8)),
                ("subject", models.CharField(blank=True, max_length=512)),
                ("body_html", models.TextField(blank=True)),
                ("body_text", models.TextField(blank=True)),
                ("is_customized", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "email_template",
                "ordering": ["slug", "language"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("slug", "language"),
                        name="email_template_slug_language_uniq",
                    )
                ],
            },
        ),
    ]
