# Generated by Django 5.2.17 on 2026-09-15 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="emaillog",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("sent", "Sent"),
                    ("delivered", "Delivered"),
                    ("bounced", "Bounced"),
                    ("deferred", "Deferred"),
                    ("complained", "Complained"),
                    ("rejected", "Rejected"),
                    ("failed", "Failed"),
                    ("suppressed", "Suppressed"),
                ],
                db_index=True,
                default="pending",
                max_length=16,
            ),
        ),
    ]
