# Generated by Django 5.2.15 on 2026-07-04 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissioning', '0002_finalized_protection_and_reference_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sharetype',
            name='gets_packed_with',
        ),
    ]
