# Generated by Django 5.2.15 on 2026-07-04 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commissioning', '0003_remove_sharetype_gets_packed_with'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sharetype',
            old_name='is_base_share_type',
            new_name='is_additional_share_type',
        ),
    ]
