# Generated by Django 5.2.15 on 2026-07-04 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commissioning",
            "0004_rename_is_base_share_type_sharetype_is_additional_share_type",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharetype",
            name="delivery_cycle",
            field=models.CharField(
                blank=True,
                choices=[
                    ("WEEKLY", "Weekly"),
                    ("ODD_WEEKS", "Odd Weeks"),
                    ("EVEN_WEEKS", "Even Weeks"),
                    ("ALL_THREE_WEEKS", "All Three Weeks"),
                    ("ALL_FOUR_WEEKS", "All Four Weeks"),
                ],
                max_length=16,
                null=True,
            ),
        ),
    ]
