# Generated by Django 5.2.15 on 2026-07-04 19:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0005_alter_sharetype_delivery_cycle"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sharetype",
            name="is_additional_share_type",
            field=models.BooleanField(default=False),
        ),
    ]
