# Generated by Django 5.2.15 on 2026-07-04 22:18

from django.conf import settings
from django.db import migrations, models

# Models that carry the mutually-exclusive washing/cleaning flags.
_FLAG_MODELS = ["Offer", "OrderContent", "ShareContent"]


def clear_both_flags(apps, schema_editor):
    """Defensive cleanup before the constraint lands.

    The planning/offers/orders UI already treats washing/cleaning as pick-one, so
    no UI-created row should have both set. But the API / imports / bulk paths could
    have written (washing=True, cleaning=True) — which the new CheckConstraint
    rejects, so an un-cleaned row would abort this migration on deploy. Resolve it
    by keeping ``washing`` and clearing ``cleaning`` (arbitrary but deterministic;
    dev has zero such rows). Runs once per tenant schema.
    """
    for model_name in _FLAG_MODELS:
        model = apps.get_model("commissioning", model_name)
        model.objects.filter(washing=True, cleaning=True).update(cleaning=False)


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0006_alter_sharetype_is_additional_share_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RunPython(clear_both_flags, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name="offer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("washing", True), ("cleaning", True), _negated=True
                ),
                name="offer_washing_cleaning_mutually_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="ordercontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("washing", True), ("cleaning", True), _negated=True
                ),
                name="ordercontent_washing_cleaning_mutually_exclusive",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharecontent",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("washing", True), ("cleaning", True), _negated=True
                ),
                name="sharecontent_washing_cleaning_mutually_exclusive",
            ),
        ),
    ]
