# Generated by Django 5.2.15 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commissioning",
            "0007_offer_offer_washing_cleaning_mutually_exclusive_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="deliverystationday",
            name="capacity",
            field=models.PositiveIntegerField(default=50),
        ),
        migrations.AlterField(
            model_name="sharetypevariation",
            name="capacity",
            field=models.IntegerField(default=100),
        ),
    ]
