# Generated by Django 5.2.15 on 2026-07-05 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0008_alter_deliverystationday_capacity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="waiting_list_reason",
            field=models.CharField(
                blank=True,
                choices=[
                    ("delivery_station_full", "Delivery station full"),
                    ("variation_full", "Share type sold out"),
                    ("manual", "Manually queued"),
                ],
                max_length=32,
                null=True,
            ),
        ),
    ]
