# Generated by Django 5.2.15 on 2026-07-05 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0009_subscription_waiting_list_reason"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="notification_token",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="subscription",
            name="notification_token",
            field=models.UUIDField(
                blank=True, db_index=True, editable=False, null=True
            ),
        ),
    ]
