# Generated by Django 5.2.15 on 2026-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0011_backfill_over_default_variation_capacity"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopshare",
            name="cancellation_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
