# Generated by Django 5.2.15 on 2026-07-06 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0012_coopshare_cancellation_reason"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("privacy", "Privacy policy"),
                    ("sepa", "SEPA Direct Debit mandate"),
                    ("withdrawal", "Withdrawal terms"),
                    ("terms", "Terms of service"),
                    ("coop_contract", "Cooperative-share subscription contract"),
                    ("subscription_contract", "Subscription contract"),
                ],
                max_length=40,
            ),
        ),
    ]
