# Generated by Django 5.2.15 on 2026-07-07 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0015_content_finalized_one_way"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharetype",
            name="short_name",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
