# Generated by Django 5.2.15 on 2026-07-10 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0016_sharetype_short_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharearticle",
            name="percentage_added_to_commissioning_list_packing",
            field=models.PositiveSmallIntegerField(default=5),
        ),
    ]
