# Generated by Django 5.2.16 on 2026-07-11 14:36

import apps.commissioning.models.base
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commissioning",
            "0017_sharearticle_percentage_added_to_commissioning_list_packing",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="reseller",
            name="organic_control_number",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.CreateModel(
            name="OrganicCertificate",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.commissioning.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateField()),
                ("valid_until", models.DateField(blank=True, null=True)),
                (
                    "certificate_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("link", models.URLField(blank=True, max_length=500, null=True)),
                (
                    "reseller",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="organic_certificates",
                        to="commissioning.reseller",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="organiccertificate_valid_range",
                    )
                ],
            },
        ),
    ]
