# Generated by Django 5.2.16 on 2026-07-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0018_reseller_organic_control_number_organiccertificate"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="organic_status",
            field=models.CharField(
                choices=[
                    ("organic", "Bio"),
                    ("in_conversion", "Umstellung"),
                    ("conventional", "Konventionell"),
                ],
                default="conventional",
                max_length=20,
            ),
        ),
    ]
