# Generated by Django 5.2.16 on 2026-07-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0019_purchase_organic_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="consentdocument",
            name="kind",
            field=models.CharField(
                choices=[
                    ("privacy", "Privacy policy"),
                    ("sepa", "SEPA Direct Debit mandate"),
                    ("withdrawal", "Withdrawal terms"),
                    ("terms", "Terms of service"),
                    ("coop_contract", "Cooperative-share subscription contract"),
                    ("coop_cancellation", "Cancellation of membership in coop"),
                    ("subscription_contract", "Subscription contract"),
                ],
                max_length=40,
            ),
        ),
    ]
