# Generated by Django 5.2.16 on 2026-07-23 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0020_alter_consentdocument_kind"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharetypevariation",
            name="allowed_for_trial_subscription",
            field=models.BooleanField(default=False),
        ),
    ]
