# Generated by Django 5.2.16 on 2026-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0021_sharetypevariation_allowed_for_trial_subscription"),
    ]

    operations = [
        migrations.AddField(
            model_name="sharetypevariationgrossprice",
            name="price_per_delivery_if_trial",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
        migrations.AddField(
            model_name="sharetypevariationgrossprice",
            name="solidarity_min_price_per_delivery_if_trial",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=6, null=True
            ),
        ),
    ]
