# Generated by Django 5.2.17 on 2026-09-11 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "commissioning",
            "0022_sharetypevariationgrossprice_price_per_delivery_if_trial_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="member",
            name="email",
            field=models.EmailField(blank=True, max_length=255, null=True),
        ),
    ]
