# Generated by Django 5.2.17 on 2026-09-15 16:35

import apps.commissioning.models.base
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0024_content_parent_move_protection"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CoopShareTransfer",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.commissioning.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("amount_of_coop_shares", models.PositiveIntegerField()),
                ("transfer_date", models.DateField()),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="%(app_label)s_%(class)s_created_by",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "from_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="commissioning.member",
                    ),
                ),
                (
                    "to_member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to="commissioning.member",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="coopshare",
            name="transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="coop_shares",
                to="commissioning.coopsharetransfer",
            ),
        ),
        migrations.AddConstraint(
            model_name="coopsharetransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("from_member", models.F("to_member")), _negated=True
                ),
                name="coopsharetransfer_distinct_members",
            ),
        ),
        migrations.AddConstraint(
            model_name="coopsharetransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("amount_of_coop_shares__gt", 0)),
                name="coopsharetransfer_amount_positive",
            ),
        ),
    ]
