# Generated by Django 5.2.17 on 2026-09-15 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0025_coop_share_transfer"),
    ]

    operations = [
        migrations.AddField(
            model_name="coopshare",
            name="settled_by_transfer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="settled_coop_shares",
                to="commissioning.coopsharetransfer",
            ),
        ),
    ]
