# Generated by Django 5.2.17 on 2026-09-17 10:29

import apps.shared.iban_validator
import django.core.validators
import encrypted_model_fields.fields
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0026_coop_share_settled_by_transfer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contactentity",
            name="iban",
            field=encrypted_model_fields.fields.EncryptedCharField(
                blank=True,
                null=True,
                validators=[apps.shared.iban_validator.IBANValidator()],
            ),
        ),
        migrations.AlterField(
            model_name="virtualvariationcomponent",
            name="quantity",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                max_digits=5,
                validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
            ),
        ),
    ]
