# Generated by Django 5.2.17 on 2026-09-17 14:01
"""GiST exclusion constraints closing the TimeBound overlap gap on nine models.

The Python ``_validate_no_overlap`` check runs from ``clean()`` only: it is
TOCTOU-racy and never runs on ``bulk_create`` / ``bulk_update`` /
``QuerySet.update()`` / raw SQL. Each constraint here rejects two rows in the
same overlap group whose inclusive ``[valid_from, valid_until]`` ranges
intersect; adjacent windows (one starting the day after the other ends) stay
legal, which is the shape ``handle_succession`` creates.

A table that already holds an overlapping pair cannot take the constraint: this
migration then FAILS LOUDLY on that table rather than skipping the rows or
installing a constraint that silently does not hold.

``btree_gist`` (needed for the scalar equality halves) is installed into
``public`` by 0001_initial and is not reinstalled here.
"""

import apps.commissioning.models.mixin
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0027_alter_contactentity_iban_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="consentdocument",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("kind", "="),
                    ("locale", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="consentdocument_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="cratenetprice",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("crate", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="cratenetprice_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliveryexceptionperiod",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("share_type_variation", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="deliveryexceptionperiod_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverystationday",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("delivery_station", "="),
                    ("delivery_day", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="deliverystationday_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="organiccertificate",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("reseller", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="organiccertificate_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharearticlenetprice",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("share_article", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="sharearticlenetprice_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharesdeliveryday",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("day_number", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="sharesdeliveryday_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharetype",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("share_option", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="sharetype_no_overlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="sharetypevariation",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    ("share_type", "="),
                    ("size", "="),
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    ),
                ],
                name="sharetypevariation_no_overlap",
            ),
        ),
    ]
