# Generated by Django 5.2.17 on 2026-09-17 17:03

import apps.commissioning.models.mixin
import django.contrib.postgres.constraints
import django.contrib.postgres.fields.ranges
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0028_consentdocument_consentdocument_no_overlap_and_more"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="season",
            constraint=django.contrib.postgres.constraints.ExclusionConstraint(
                expressions=[
                    (
                        apps.commissioning.models.mixin.InclusiveDateRange(
                            "valid_from",
                            "valid_until",
                            django.contrib.postgres.fields.ranges.RangeBoundary(
                                inclusive_lower=True, inclusive_upper=True
                            ),
                        ),
                        "&&",
                    )
                ],
                name="season_no_overlap",
            ),
        ),
    ]
