# Generated by Django 5.2.17 on 2026-10-08 20:09

"""Adds the storage to the waste's per-day uniqueness.

The new key only widens what is allowed, so every existing row satisfies it.
The new constraint is added before the old one goes, so the table is never
without one. The reverse restores the narrower key; it fails, and changes
nothing, once two wastes of a day differ only by their storage.
"""

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("commissioning", "0030_date_transfer_exits_by_the_latest_transfer"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="waste",
            constraint=models.UniqueConstraint(
                condition=models.Q(("day_number__isnull", False)),
                fields=(
                    "year",
                    "delivery_week",
                    "day_number",
                    "share_article",
                    "unit",
                    "size",
                    "storage",
                ),
                name="waste_unique_year_week_day_article_unit_size_storage",
            ),
        ),
        migrations.RemoveConstraint(
            model_name="waste",
            name="waste_unique_year_week_day_article_unit_size",
        ),
    ]
