# Generated by Django 5.2.15 on 2026-07-03 21:33

import apps.shared.iban_validator
import apps.shared.tenants.models
import django.core.validators
import django.db.models.deletion
import django_tenants.postgresql_backend.base
import encrypted_model_fields.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tenant",
            fields=[
                (
                    "schema_name",
                    models.CharField(
                        db_index=True,
                        max_length=63,
                        unique=True,
                        validators=[
                            django_tenants.postgresql_backend.base._check_schema_name
                        ],
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("address", models.CharField(blank=True, max_length=200, null=True)),
                ("zip_code", models.CharField(blank=True, max_length=10, null=True)),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("country", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "organic_control_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "tenant_language",
                    models.CharField(blank=True, default="en", max_length=8),
                ),
                (
                    "phone_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                (
                    "email_for_orders",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                ("website", models.URLField(blank=True, null=True)),
                (
                    "legal_form",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                (
                    "data_protection_contact",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("dpo", models.CharField(blank=True, default="", max_length=200)),
                (
                    "supervisory_authority",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("currency", models.CharField(default="EUR", max_length=8)),
                (
                    "timezone",
                    models.CharField(
                        default="UTC",
                        help_text="Frontend display only. The Django backend uses the process-level ``TIME_ZONE`` (settings.py) for every ``timezone.localdate()`` / ``timezone.now()`` call — it does NOT switch per tenant. Onboarding a tenant in a different zone would silently get the server's concept of 'today' for backend business logic. If multi-region tenants ever become a real product requirement, every ``timezone.localdate()`` callsite needs to flow through this field.",
                        max_length=64,
                    ),
                ),
                ("date_format", models.CharField(default="DD.MM.YYYY", max_length=32)),
                ("time_format", models.CharField(default="HH:mm", max_length=16)),
                ("csv_format", models.CharField(default="de", max_length=8)),
                ("number_locale", models.CharField(default="de-DE", max_length=16)),
                ("navigation", models.JSONField(blank=True, default=dict)),
                ("ai", models.JSONField(blank=True, default=dict)),
                ("allow_upload_for_data_lists", models.BooleanField(default=True)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="logos/")),
                (
                    "bio_logo",
                    models.ImageField(blank=True, null=True, upload_to="bio_logos/"),
                ),
                (
                    "fiscal_year_start_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ],
                    ),
                ),
                (
                    "iban",
                    models.CharField(
                        blank=True,
                        max_length=34,
                        null=True,
                        validators=[apps.shared.iban_validator.IBANValidator()],
                    ),
                ),
                ("uid", models.CharField(blank=True, max_length=20, null=True)),
                ("days_until_payment_due", models.IntegerField(default=14)),
                (
                    "sepa_creditor_id",
                    models.CharField(blank=True, default="", max_length=35),
                ),
                (
                    "sepa_creditor_name",
                    models.CharField(blank=True, default="", max_length=70),
                ),
                (
                    "sepa_creditor_bic",
                    models.CharField(blank=True, default="", max_length=11),
                ),
                (
                    "sepa_remittance_template",
                    models.CharField(blank=True, default="", max_length=140),
                ),
                ("privacy_policy_html", models.TextField(blank=True, default="")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Domain",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "domain",
                    models.CharField(db_index=True, max_length=253, unique=True),
                ),
                ("is_primary", models.BooleanField(db_index=True, default=True)),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="domains",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TenantEmailConfig",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("smtp_host", models.CharField(blank=True, max_length=255, null=True)),
                ("smtp_port", models.IntegerField(blank=True, default=587, null=True)),
                (
                    "smtp_username",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "smtp_password",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, null=True
                    ),
                ),
                ("smtp_use_tls", models.BooleanField(default=True)),
                (
                    "from_email",
                    models.EmailField(
                        help_text="Default 'From' email address",
                        max_length=254,
                        validators=[django.core.validators.EmailValidator()],
                    ),
                ),
                (
                    "from_name",
                    models.CharField(
                        help_text="Display name for 'From' field", max_length=255
                    ),
                ),
                (
                    "reply_to_email",
                    models.EmailField(blank=True, max_length=254, null=True),
                ),
                (
                    "accounting_email",
                    models.EmailField(
                        blank=True,
                        help_text="Email address for sending invoices to accounting (e.g., DATEV)",
                        max_length=254,
                        null=True,
                    ),
                ),
                ("max_emails_per_hour", models.IntegerField(default=1000)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False,
                        help_text="Set to True when a test send through this SMTP host succeeds.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "tenant",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="email_config",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Tenant Email Configuration",
                "verbose_name_plural": "Tenant Email Configurations",
                "db_table": "tenant_email_config",
            },
        ),
        migrations.CreateModel(
            name="TenantSettings",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("valid_from", models.DateTimeField()),
                ("valid_until", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("has_coop_shares", models.BooleanField(default=True)),
                (
                    "coop_shares_payment_after_admin_confirmation_in_days",
                    models.IntegerField(default=14),
                ),
                ("uses_member_loans", models.BooleanField(default=False)),
                ("value_one_coop_share", models.PositiveIntegerField(default=100)),
                ("min_number_coop_shares", models.PositiveIntegerField(default=3)),
                ("max_number_coop_shares", models.PositiveIntegerField(default=100)),
                (
                    "retention_period_cancelled_members_coop_shares_in_months",
                    models.PositiveIntegerField(default=0),
                ),
                (
                    "season_start_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "min_weeks_from_creation_to_start_delivery",
                    models.PositiveIntegerField(default=2),
                ),
                (
                    "allows_additional_subscriptions_without_base_share_type",
                    models.BooleanField(default=True),
                ),
                ("allows_share_variation_optin", models.BooleanField(default=False)),
                ("allows_trial_subscriptions", models.BooleanField(default=True)),
                (
                    "allowed_trial_subscription_duration",
                    models.PositiveIntegerField(default=4),
                ),
                (
                    "allows_trial_subscriptions_for_trial_members",
                    models.BooleanField(default=True),
                ),
                (
                    "info_sentence_about_trial_subscriptions",
                    models.TextField(blank=True, null=True),
                ),
                ("uses_jokers", models.BooleanField(default=True)),
                ("default_amount_of_jokers", models.PositiveIntegerField(default=4)),
                (
                    "uses_jokers_for_trial_subscriptions",
                    models.BooleanField(default=False),
                ),
                ("uses_donation_jokers", models.BooleanField(default=False)),
                (
                    "default_amount_of_additional_donation_jokers",
                    models.PositiveIntegerField(default=3),
                ),
                (
                    "packing_mode",
                    models.CharField(
                        choices=[
                            ("BOXES", "Boxes (pre-packed per station)"),
                            ("BULK", "Bulk (members pick from crates)"),
                            ("MIXED", "Mixed (per share-type variation)"),
                        ],
                        default="BOXES",
                        max_length=10,
                    ),
                ),
                (
                    "percentage_added_to_bulk_packing_list",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("number_packing_stations", models.PositiveIntegerField(default=1)),
                ("allows_solidarity_pricing", models.BooleanField(default=False)),
                ("show_size_column", models.BooleanField(default=True)),
                (
                    "show_summary_in_harvest_share_planning_on_top",
                    models.BooleanField(default=True),
                ),
                (
                    "show_seller_name_of_share_article_in_share_for_member_on_page",
                    models.BooleanField(default=True),
                ),
                ("round_up_to_full_pu_harvesting", models.BooleanField(default=False)),
                ("has_markets", models.BooleanField(default=True)),
                ("sells_to_resellers", models.BooleanField(default=True)),
                (
                    "payment_terms_reseller_in_days",
                    models.PositiveIntegerField(default=14),
                ),
                (
                    "early_payment_discount_percent",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                (
                    "early_payment_discount_days",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                (
                    "order_numbers_start_new_at_year_change",
                    models.BooleanField(default=False),
                ),
                ("order_number_prefix", models.CharField(default="BE", max_length=10)),
                (
                    "delivery_note_numbers_start_new_at_year_change",
                    models.BooleanField(default=False),
                ),
                (
                    "delivery_note_number_prefix",
                    models.CharField(default="LS", max_length=10),
                ),
                (
                    "invoice_numbers_start_new_at_year_change",
                    models.BooleanField(default=False),
                ),
                (
                    "invoice_number_prefix",
                    models.CharField(default="RE", max_length=10),
                ),
                (
                    "correction_invoice_number_prefix",
                    models.CharField(default="RK", max_length=10),
                ),
                (
                    "left_column_footer_documents_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "middle_column_footer_documents_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "right_column_footer_documents_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_1_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_2_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_3_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_1_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_2_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_3_invoice_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_1_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_2_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_3_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_1_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_2_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_3_delivery_note_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_1_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_2_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "entry_line_3_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_1_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_2_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "greeting_line_3_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "order_instructions_offer_reseller",
                    models.TextField(blank=True, null=True),
                ),
                (
                    "used_tiers_for_offers",
                    models.JSONField(blank=True, default=list, null=True),
                ),
                ("offer_prices_are_per_pu", models.BooleanField(default=False)),
                ("use_personalized_offers", models.BooleanField(default=True)),
                (
                    "subscriptions_end_at_end_of_season",
                    models.BooleanField(default=False),
                ),
                ("subscriptions_end_after_one_year", models.BooleanField(default=True)),
                ("subscriptions_are_auto_renewed", models.BooleanField(default=False)),
                (
                    "min_weeks_to_cancel_before_ending",
                    models.PositiveIntegerField(default=6),
                ),
                (
                    "allows_share_type_variation_change",
                    models.BooleanField(default=False),
                ),
                (
                    "max_share_type_variation_changes",
                    models.PositiveIntegerField(default=1),
                ),
                ("allows_delivery_station_change", models.BooleanField(default=False)),
                (
                    "max_delivery_station_changes",
                    models.PositiveIntegerField(default=1),
                ),
                (
                    "default_planning_granularity",
                    models.CharField(
                        choices=[
                            ("basic", "Basic"),
                            ("tours", "Tours"),
                            ("stations", "Stations"),
                        ],
                        default="basic",
                        max_length=10,
                    ),
                ),
                ("uses_pledge_round", models.BooleanField(default=False)),
                ("uploads_weekly_share_amount", models.BooleanField(default=False)),
                (
                    "default_tax_rate_articles",
                    models.DecimalField(decimal_places=2, default=7, max_digits=5),
                ),
                (
                    "default_tax_rate_crates",
                    models.DecimalField(decimal_places=2, default=19, max_digits=5),
                ),
                (
                    "default_tax_rate_shares",
                    models.DecimalField(decimal_places=2, default=7, max_digits=5),
                ),
                (
                    "billing_strategy",
                    models.CharField(
                        choices=[
                            (
                                "EXACT_PER_PERIOD",
                                "Exact per period (count actual deliveries)",
                            ),
                            ("SMOOTHED", "Smoothed across subscription term"),
                        ],
                        default="EXACT_PER_PERIOD",
                        max_length=20,
                    ),
                ),
                (
                    "bills_joker_deliveries",
                    models.BooleanField(
                        default=False,
                        help_text="If false, ShareDelivery rows with joker_taken=True are not billed.",
                    ),
                ),
                (
                    "billing_due_day_of_month",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Day of month the charge is due. Capped at 28 to avoid month-length issues.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "sepa_collection_day_of_month",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Default day of month on which the bank should execute SEPA direct-debit collections. Used to derive the RequestedCollectionDate when an office user creates a billing run by month. Adjusted forward for SEPA lead times and TARGET banking days.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(28),
                        ],
                    ),
                ),
                (
                    "require_admin_approval_for_gdpr_deletion",
                    models.BooleanField(
                        default=True,
                        help_text="If on (default), every deletion request needs an office/admin to approve after the email-confirm step. Turn off to honour Art. 17 requests automatically once the user clicks the email link. Staff/admin deletions always need admin approval regardless of this.",
                    ),
                ),
                (
                    "requires_paper_signature_for_membership",
                    models.BooleanField(default=False),
                ),
                (
                    "requires_paper_signature_for_sepa_mandate",
                    models.BooleanField(default=False),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tenant_settings",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-valid_from"],
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("valid_until__isnull", True)),
                        fields=("tenant",),
                        name="tenantsettings_one_current_per_tenant",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("valid_until__isnull", True),
                            ("valid_until__gte", models.F("valid_from")),
                            _connector="OR",
                        ),
                        name="tenantsettings_valid_until_after_valid_from",
                    ),
                ],
            },
        ),
    ]
