# Generated by Django 5.2.15 on 2026-07-04 13:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tenantsettings',
            name='allows_additional_subscriptions_without_base_share_type',
        ),
    ]
