# Generated by Django 5.2.15 on 2026-07-08 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0003_rename_tenantsettings_allows_share_type_variation_optin"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="allows_waiting_list_for_subscriptions",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="tenantsettings",
            name="reservation_ttl_days",
            field=models.PositiveIntegerField(default=14),
        ),
    ]
