# Generated by Django 5.2.15 on 2026-07-09 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0004_tenantsettings_allows_waiting_list_for_subscriptions_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="has_markets",
            field=models.BooleanField(default=False),
        ),
    ]
