# Generated by Django 5.2.15 on 2026-07-10 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0006_tenant_auditing_association_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="allows_self_registration",
            field=models.BooleanField(default=False),
        ),
    ]
