# Generated by Django 5.2.15 on 2026-07-10 12:17

import apps.shared.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0007_tenantsettings_allows_self_registration"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="action_rate_limit_overrides",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="ActionRateLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(max_length=63)),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("invoice_finalization", "Invoice finalization"),
                            (
                                "delivery_note_finalization",
                                "Delivery-note finalization",
                            ),
                            ("sepa_charge_generation", "SEPA charge generation"),
                            ("member_creation", "Member creation"),
                            ("user_creation", "User creation"),
                            ("subscription_confirmation", "Subscription confirmation"),
                        ],
                        max_length=40,
                    ),
                ),
                ("actor_id", models.CharField(blank=True, default="", max_length=12)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["tenant_schema", "action", "created_at"],
                        name="actionratelog_lookup_idx",
                    )
                ],
            },
        ),
    ]
