# Generated by Django 5.2.15 on 2026-07-10 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0008_tenant_action_rate_limit_overrides_actionratelog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenant",
            name="action_rate_limit_overrides",
            field=models.JSONField(blank=True, default=dict, editable=False),
        ),
    ]
