# Generated by Django 5.2.16 on 2026-07-21 20:02

import apps.shared.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0009_alter_tenant_action_rate_limit_overrides"),
    ]

    operations = [
        migrations.AlterField(
            model_name="actionratelog",
            name="id",
            field=models.CharField(
                default=apps.shared.tenants.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tenant",
            name="id",
            field=models.CharField(
                default=apps.shared.tenants.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="tenantsettings",
            name="id",
            field=models.CharField(
                default=apps.shared.tenants.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
