# Generated by Django 5.2.16 on 2026-07-22 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0010_alter_actionratelog_id_alter_tenant_id_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="distribute_forecast_by_weight",
            field=models.BooleanField(default=False),
        ),
    ]
