# Generated by Django 5.2.15 on 2026-07-23 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0011_tenantsettings_distribute_forecast_by_weight"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="crates_should_be_on_documents",
            field=models.BooleanField(default=True),
        ),
    ]
