# Generated by Django 5.2.16 on 2026-07-23 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0012_tenantsettings_crates_should_be_on_documents"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="requires_paper_signature_for_cancellation_of_membership",
            field=models.BooleanField(default=False),
        ),
    ]
