# Generated by Django 5.2.16 on 2026-07-23 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "tenants",
            "0013_tenantsettings_requires_paper_signature_for_cancellation_of_membership",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantsettings",
            name="trial_subscriptions_have_different_prices",
            field=models.BooleanField(default=False),
        ),
    ]
