# Generated by Django 5.2.16 on 2026-07-24 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0014_tenantsettings_trial_subscriptions_have_different_prices"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenantemailconfig",
            name="smtp_use_ssl",
            field=models.BooleanField(default=False),
        ),
    ]
