# Generated by Django 5.2.16 on 2026-08-16 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0015_tenantemailconfig_smtp_use_ssl"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenant",
            name="app_icon",
            field=models.ImageField(blank=True, null=True, upload_to="app_icons/"),
        ),
        migrations.AddField(
            model_name="tenant",
            name="app_short_name",
            field=models.CharField(blank=True, default="", max_length=12),
        ),
    ]
