# Generated by Django 5.2.17 on 2026-09-17 10:29

import apps.shared.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tenants", "0017_tenantsettings_onboarding_mode"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenantsettings",
            name="used_tiers_for_offers",
            field=models.JSONField(
                blank=True,
                default=list,
                null=True,
                validators=[apps.shared.tenants.models.validate_offer_tiers],
            ),
        ),
    ]
