# Generated by Django 5.2.15 on 2026-07-03 21:33

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Account",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("account_type", models.CharField(max_length=50)),
                ("account_number", models.CharField(max_length=20, unique=True)),
                ("account_name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AccountValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "month",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(12),
                        ]
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("real_value", models.BooleanField(default=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="economics.account",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "month"],
                "unique_together": {("year", "month", "account")},
            },
        ),
    ]
