# Generated by Django 5.2.16 on 2026-07-28 12:04

import apps.cultivation.models.base
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Plot",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("is_greenhouse", models.BooleanField(default=False)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeedlingsVendor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="SeedsVendor",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("email", models.CharField(blank=True, max_length=200, null=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="BedType",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=200, null=True)),
                ("length_in_m", models.IntegerField()),
                ("width_in_m", models.DecimalField(decimal_places=2, max_digits=4)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("length_in_m__gt", 0)),
                        name="bedtype_length_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("width_in_m__gt", 0)),
                        name="bedtype_width_positive",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="CultivationBreakFamily",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("cultivation_break_in_years", models.PositiveSmallIntegerField()),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="uniq_cultivationbreakfamily_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CultivationPlanSolution",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("version", models.PositiveSmallIntegerField()),
                ("chosen", models.BooleanField(default=False)),
                ("cells_per_bed", models.PositiveSmallIntegerField(default=5)),
            ],
            options={
                "ordering": ["-year", "version"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("year", "version"), name="uniq_solution_year_version"
                    ),
                    models.UniqueConstraint(
                        condition=models.Q(("chosen", True)),
                        fields=("year",),
                        name="one_chosen_solution_per_year",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Vegetable",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "unit",
                    models.CharField(
                        choices=[("KG", "Kg"), ("PCS", "Pcs"), ("BUNCH", "Bunch")],
                        max_length=10,
                    ),
                ),
                (
                    "average_kg_per_piece",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                ("default_planting_lines", models.IntegerField()),
                (
                    "default_distance_in_row",
                    models.DecimalField(decimal_places=2, max_digits=4),
                ),
                (
                    "default_planting_mode",
                    models.CharField(
                        choices=[("PLANTING", "P"), ("SOWING", "S")], max_length=10
                    ),
                ),
                (
                    "default_pieces_per_plant",
                    models.IntegerField(blank=True, null=True),
                ),
                (
                    "default_yield_kg_per_m2",
                    models.DecimalField(
                        blank=True, decimal_places=3, max_digits=5, null=True
                    ),
                ),
                (
                    "fertilizer_requirement",
                    models.CharField(
                        choices=[
                            ("WEAK", "Weak"),
                            ("MIDDLE", "Middle"),
                            ("STRONG", "Strong"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "cultivation_break_family",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="vegetables",
                        to="cultivation.cultivationbreakfamily",
                    ),
                ),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.CreateModel(
            name="HistoricalPlanting",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                ("start_cell", models.PositiveIntegerField()),
                ("cell_count", models.PositiveSmallIntegerField()),
                (
                    "occupied_until_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "cultivation_break_family",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_plantings",
                        to="cultivation.cultivationbreakfamily",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="historical_plantings",
                        to="cultivation.plot",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="cultivation.vegetable",
                    ),
                ),
            ],
            options={
                "ordering": ["-year"],
            },
        ),
        migrations.CreateModel(
            name="VegetableAggregation",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
            options={
                "ordering": ["name"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name",), name="uniq_vegetableaggregation_name"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CultivationBatch",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveSmallIntegerField()),
                (
                    "planting_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ]
                    ),
                ),
                (
                    "week_when_net_is_removed",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "week_when_fleece_is_removed",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "harvesting_start_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ]
                    ),
                ),
                (
                    "harvesting_end_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ]
                    ),
                ),
                (
                    "delivery_start_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "delivery_end_week",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ],
                    ),
                ),
                (
                    "end_week",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(53),
                        ]
                    ),
                ),
                ("planting_lines", models.PositiveSmallIntegerField()),
                (
                    "distance_in_row_in_m",
                    models.DecimalField(decimal_places=3, max_digits=5),
                ),
                (
                    "planting_mode",
                    models.CharField(
                        choices=[("PLANTING", "P"), ("SOWING", "S")], max_length=10
                    ),
                ),
                ("seedlings_are_produced_on_site", models.BooleanField(default=False)),
                (
                    "pieces_per_plant",
                    models.DecimalField(decimal_places=1, max_digits=3),
                ),
                (
                    "yield_kg_per_m2",
                    models.DecimalField(decimal_places=2, max_digits=5),
                ),
                (
                    "amount_of_beds",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=5, null=True
                    ),
                ),
                ("growing_area_m2", models.IntegerField(blank=True, null=True)),
                ("note", models.CharField(blank=True, max_length=200, null=True)),
                ("is_final", models.BooleanField(default=False)),
                (
                    "used_bed_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cultivation.bedtype",
                    ),
                ),
                (
                    "vegetable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="batches",
                        to="cultivation.vegetable",
                    ),
                ),
                (
                    "vegetable_set",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="batches",
                        to="cultivation.vegetableaggregation",
                    ),
                ),
            ],
            options={
                "ordering": ["year", "planting_week"],
            },
        ),
        migrations.CreateModel(
            name="CultivationPlanSolutionDetail",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("start_cell", models.PositiveIntegerField()),
                ("cell_count", models.PositiveSmallIntegerField()),
                (
                    "batch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cultivation.cultivationbatch",
                    ),
                ),
                (
                    "solution",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="cultivation.cultivationplansolution",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cultivation.plot",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["solution", "plot"],
                        name="cultivation_solutio_ca4139_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("cell_count__gt", 0)),
                        name="solutiondetail_cell_count_positive",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="PlotContent",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.PositiveIntegerField()),
                (
                    "bed_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="cultivation.bedtype",
                    ),
                ),
                (
                    "plot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contents",
                        to="cultivation.plot",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("plot", "bed_type"),
                        name="uniq_plotcontent_plot_bedtype",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("amount__gt", 0)),
                        name="plotcontent_amount_positive",
                    ),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="vegetable",
            constraint=models.UniqueConstraint(
                fields=("name",), name="uniq_vegetable_name"
            ),
        ),
        migrations.AddConstraint(
            model_name="vegetable",
            constraint=models.CheckConstraint(
                condition=models.Q(("average_kg_per_piece__gt", 0)),
                name="vegetable_avg_kg_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="historicalplanting",
            index=models.Index(
                fields=["year", "plot"], name="cultivation_year_f3a62a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="historicalplanting",
            index=models.Index(
                fields=["year", "cultivation_break_family"],
                name="cultivation_year_6daa36_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalplanting",
            constraint=models.CheckConstraint(
                condition=models.Q(("cell_count__gt", 0)),
                name="historicalplanting_cell_count_positive",
            ),
        ),
        migrations.AddIndex(
            model_name="cultivationbatch",
            index=models.Index(
                fields=["year", "is_final"], name="cultivation_year_b4f961_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("planting_lines__gt", 0)),
                name="cultivationbatch_planting_lines_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("distance_in_row_in_m__gt", 0)),
                name="cultivationbatch_distance_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("pieces_per_plant__gt", 0)),
                name="cultivationbatch_pieces_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(("yield_kg_per_m2__gte", 0)),
                name="cultivationbatch_yield_non_negative",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("amount_of_beds__isnull", True),
                    ("amount_of_beds__gt", 0),
                    _connector="OR",
                ),
                name="cultivationbatch_beds_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="cultivationbatch",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("growing_area_m2__isnull", True),
                    ("growing_area_m2__gt", 0),
                    _connector="OR",
                ),
                name="cultivationbatch_area_positive",
            ),
        ),
    ]
