# Generated by Django 5.2.16 on 2026-07-29 11:11

import apps.cultivation.models.base
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultivation", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="SolverSettings",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.cultivation.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                (
                    "solver_max_time_seconds",
                    models.PositiveSmallIntegerField(
                        default=60,
                        help_text="Wall-clock budget for ONE solve. Capped at 900s so a mistyped value cannot pin a worker for hours.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(900),
                        ],
                    ),
                ),
                (
                    "solver_workers",
                    models.PositiveSmallIntegerField(
                        default=8,
                        help_text="CP-SAT search worker threads (num_search_workers).",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(32),
                        ],
                    ),
                ),
                (
                    "default_num_solutions",
                    models.PositiveSmallIntegerField(
                        default=4,
                        help_text="How many distinct candidate plans one run produces.",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                    ),
                ),
                (
                    "enable_planting_line_homogeneity",
                    models.BooleanField(
                        default=True,
                        help_text="Within one bed, crops growing at the same time must share a planting line (hard constraint).",
                    ),
                ),
                (
                    "enable_fleece",
                    models.BooleanField(
                        default=False,
                        help_text="Cover fleece-needing crops with 4-bed-wide fleece units (hard) and minimise fleece-weeks (soft). Expensive: adds per-(plot, week, bed) variables.",
                    ),
                ),
                (
                    "enable_line_dispersion",
                    models.BooleanField(
                        default=False,
                        help_text="Keep beds sharing a planting line near each other (soft, aesthetic). The priciest soft term.",
                    ),
                ),
                (
                    "weight_plots_used",
                    models.PositiveSmallIntegerField(
                        default=100,
                        help_text="Consolidate the plan onto as few plots as possible.",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "weight_beds_used",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Fewer distinct beds across the season (rewards succession).",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "weight_beds_per_batch",
                    models.PositiveSmallIntegerField(
                        default=5,
                        help_text="Keep each batch bed-aligned (spanning fewest beds).",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "weight_compact_span",
                    models.PositiveSmallIntegerField(
                        default=3,
                        help_text="No gaps between the first and last used bed of a plot.",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "weight_line_dispersion",
                    models.PositiveSmallIntegerField(
                        default=1,
                        help_text="Group beds that share a planting line.",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                (
                    "weight_fleece_count",
                    models.PositiveSmallIntegerField(
                        default=10,
                        help_text="Minimise how many fleece-weeks the plan needs.",
                        validators=[django.core.validators.MaxValueValidator(1000)],
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        condition=models.Q(("is_active", True)),
                        fields=("is_active",),
                        name="solversettings_single_active",
                    )
                ],
            },
        ),
    ]
