# Generated by Django 5.2.16 on 2026-07-29 12:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultivation", "0002_solversettings"),
    ]

    operations = [
        migrations.AlterField(
            model_name="solversettings",
            name="solver_max_time_seconds",
            field=models.PositiveSmallIntegerField(
                default=60,
                help_text="Wall-clock budget for ONE solve. A hard plan legitimately needs 10+ minutes, so this goes up to 2 hours; the default stays low for quick feedback. A run computes several plans, so the total is this times the number of solutions.",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(7200),
                ],
            ),
        ),
    ]
