# Generated by Django 5.2.16 on 2026-07-29 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultivation", "0003_alter_solversettings_solver_max_time_seconds"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="cultivationbatch",
            name="cultivation_year_b4f961_idx",
        ),
        migrations.AddField(
            model_name="cultivationbatch",
            name="is_greenhouse",
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name="cultivationbatch",
            index=models.Index(
                fields=["year", "is_final", "is_greenhouse"],
                name="cultivation_year_b6962b_idx",
            ),
        ),
    ]
