# Generated by Django 5.2.16 on 2026-07-29 18:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "cultivation",
            "0004_remove_cultivationbatch_cultivation_year_b4f961_idx_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="solversettings",
            name="weight_beds_per_batch",
            field=models.PositiveSmallIntegerField(
                default=0,
                help_text="Keep each batch bed-aligned (spanning fewest beds). Defaults to 0: a crop may run from one bed into the next, and forcing bed-aligned starts strands the leftover cells of every bed, which wastes land.",
                validators=[django.core.validators.MaxValueValidator(1000)],
            ),
        ),
    ]
