# Generated by Django 5.2.16 on 2026-07-29 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cultivation", "0005_alter_solversettings_weight_beds_per_batch"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="cultivationplansolutiondetail",
            constraint=models.UniqueConstraint(
                fields=("solution", "batch"),
                name="uniq_placement_per_batch_in_solution",
            ),
        ),
    ]
