# Generated by Django 5.2.16 on 2026-07-31 17:03

from django.db import migrations, models


def number_existing_blocks(apps, schema_editor):
    """Give every plot's bed-type blocks an explicit 1..N layout order.

    Before this field a plot's bed types had NO order — capacity was a plain sum
    and no cell index was attached to a bed type — so there is no prior intent to
    recover here. Whatever order this picks is the order the plot's cells will be
    numbered in from now on, and the gardener has to confirm it matches the field.

    It is therefore chosen to be *predictable* rather than to pretend it is
    meaningful: alphabetical by bed-type name. Note that ordering by pk would NOT
    give entry order — these are random nanoids, not an increasing sequence — so
    it would produce a different arbitrary layout on every environment for the
    same data. Alphabetical at least lands on the same answer everywhere and is
    something a human can look at and reorder deliberately.
    """
    PlotContent = apps.get_model("cultivation", "PlotContent")
    seen: dict[str, int] = {}
    updates = []
    for content in PlotContent.objects.order_by("plot_id", "bed_type__name", "pk"):
        seen[content.plot_id] = seen.get(content.plot_id, 0) + 1
        content.position = seen[content.plot_id]
        updates.append(content)
    if updates:
        PlotContent.objects.bulk_update(updates, ["position"], batch_size=500)


class Migration(migrations.Migration):

    dependencies = [
        (
            "cultivation",
            "0006_cultivationplansolutiondetail_uniq_placement_per_batch_in_solution",
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="plotcontent",
            options={"ordering": ["position", "pk"]},
        ),
        migrations.AddField(
            model_name="plotcontent",
            name="position",
            field=models.PositiveSmallIntegerField(default=0),
        ),
        # reverse=noop: the column is dropped on the way back, so there is
        # nothing to restore.
        migrations.RunPython(number_existing_blocks, migrations.RunPython.noop),
    ]
