# Generated by Django 5.2.15 on 2026-07-03 21:33

import apps.shared.tenants.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DeletionLog",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(
                        help_text="Email of the user whose data was deleted (for audit trail).",
                        max_length=254,
                    ),
                ),
                ("deleted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="What data was deleted (e.g. 'Full account anonymization').",
                        null=True,
                    ),
                ),
            ],
            options={
                "ordering": ["-deleted_at"],
            },
        ),
        migrations.CreateModel(
            name="DeletionRequest",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("admin_confirmed", models.BooleanField(default=False)),
                ("admin_confirmed_at", models.DateTimeField(blank=True, null=True)),
                ("admin_rejected_at", models.DateTimeField(blank=True, null=True)),
                ("admin_rejection_reason", models.TextField(blank=True, null=True)),
                (
                    "requested_email",
                    models.EmailField(
                        help_text="Email at the moment the request was made — captured so the audit trail survives the anonymization itself.",
                        max_length=254,
                    ),
                ),
                (
                    "requested_at",
                    models.DateTimeField(auto_now_add=True, db_index=True),
                ),
                (
                    "requested_ip",
                    models.GenericIPAddressField(blank=True, db_index=True, null=True),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("pending_email", "Pending email confirmation"),
                            ("pending_admin", "Pending admin approval"),
                            ("approved", "Approved (ready to execute)"),
                            ("executed", "Executed"),
                            ("expired", "Expired (no email confirmation in time)"),
                            ("cancelled", "Cancelled"),
                            ("rejected", "Rejected by admin"),
                        ],
                        db_index=True,
                        default="pending_email",
                        max_length=20,
                    ),
                ),
                (
                    "token",
                    models.UUIDField(db_index=True, default=uuid.uuid4, unique=True),
                ),
                ("token_expires_at", models.DateTimeField()),
                ("email_confirmed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "email_confirmed_ip",
                    models.GenericIPAddressField(blank=True, null=True),
                ),
                (
                    "requires_admin_approval",
                    models.BooleanField(
                        default=True,
                        help_text="True (default) means an office/admin must approve after the email-confirm step. Set at create time by ``GDPRService.request_deletion`` from tenant settings + persona role; never flipped on a live request.",
                    ),
                ),
                ("executed_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                (
                    "admin_confirmed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_confirmations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "deletion_log",
                    models.ForeignKey(
                        blank=True,
                        help_text="Pointer to the audit-log row written when the request was actually executed.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="gdpr.deletionlog",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="deletion_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-requested_at"],
                "indexes": [
                    models.Index(
                        fields=["user", "state"], name="gdpr_deleti_user_id_f9f738_idx"
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email_confirmed_at__isnull", True),
                            ("email_confirmed_at__gte", models.F("requested_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_email_confirmed_after_requested",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("admin_confirmed_at__isnull", True),
                            ("email_confirmed_at__isnull", True),
                            ("admin_confirmed_at__gte", models.F("email_confirmed_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_admin_confirmed_after_email_confirmed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("executed_at__isnull", True),
                            ("admin_confirmed_at__isnull", True),
                            ("executed_at__gte", models.F("admin_confirmed_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_executed_after_admin_confirmed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("executed_at__isnull", True),
                            ("email_confirmed_at__isnull", True),
                            ("executed_at__gte", models.F("email_confirmed_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_executed_after_email_confirmed",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("email_confirmed_at__isnull", True),
                            ("email_confirmed_at__lte", models.F("token_expires_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_email_confirmed_before_token_expiry",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("superseded_at__isnull", True),
                            ("superseded_at__gte", models.F("requested_at")),
                            _connector="OR",
                        ),
                        name="deletionrequest_superseded_after_requested",
                    ),
                ],
            },
        ),
    ]
