# Generated by Django 5.2.15 on 2026-07-03 21:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="OpsChecklistItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("rotate_django_secret", "Rotate DJANGO_SECRET_KEY"),
                            ("rotate_field_encryption", "Rotate FIELD_ENCRYPTION_KEY"),
                            ("rotate_db_password", "Rotate Postgres password"),
                            ("rotate_bunny_token", "Rotate Bunny CDN API token"),
                            ("rotate_email_creds", "Rotate email-provider credentials"),
                            ("restore_drill", "Restore-from-backup drill"),
                            ("postgres_security_upgrade", "Postgres security upgrade"),
                            ("apt_upgrade", "OS apt upgrade"),
                            (
                                "user_account_review",
                                "Review super-admin + admin accounts",
                            ),
                            ("dependency_audit", "Manual dependency audit"),
                            ("penetration_test", "External penetration test"),
                            ("csp_audit", "CSP allowlist audit"),
                            ("custom", "Custom"),
                        ],
                        max_length=64,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Runbook notes — what to actually do, where the keys live, links to relevant docs. Read by future-you at 02:00 during the next rotation, so be generous.",
                    ),
                ),
                (
                    "interval_days",
                    models.PositiveIntegerField(
                        help_text="Reminder fires this many days after the most recent run."
                    ),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "ops_checklist_item",
                "ordering": ["title"],
            },
        ),
        migrations.CreateModel(
            name="SuperAdmin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(blank=True, max_length=30)),
                ("last_name", models.CharField(blank=True, max_length=30)),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("is_staff", models.BooleanField(default=True)),
                ("is_superuser", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "super_admin",
            },
        ),
        migrations.CreateModel(
            name="SuperAdminBlacklistedToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jti", models.CharField(db_index=True, max_length=255, unique=True)),
                ("expires_at", models.DateTimeField(db_index=True)),
                (
                    "reason",
                    models.CharField(blank=True, default="logout", max_length=64),
                ),
            ],
            options={
                "db_table": "super_admin_blacklisted_token",
            },
        ),
        migrations.CreateModel(
            name="OpsChecklistRun",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Free-form: what changed, what was rotated, what worked.",
                    ),
                ),
                (
                    "item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="runs",
                        to="super_admin.opschecklistitem",
                    ),
                ),
                (
                    "completed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to="super_admin.superadmin",
                    ),
                ),
            ],
            options={
                "db_table": "ops_checklist_run",
                "ordering": ["-completed_at"],
            },
        ),
    ]
