# Generated by Django 5.2.16 on 2026-07-15 23:38

import apps.shared.tenants.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SupportTicket",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("tenant_schema", models.CharField(db_index=True, max_length=63)),
                ("subject", models.CharField(max_length=200)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In progress"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        db_index=True,
                        default="open",
                        max_length=20,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("normal", "Normal"),
                            ("high", "High"),
                        ],
                        default="normal",
                        max_length=10,
                    ),
                ),
                ("creator_id", models.CharField(max_length=12)),
                (
                    "creator_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                (
                    "creator_email",
                    models.CharField(blank=True, default="", max_length=254),
                ),
                ("creator_roles", models.JSONField(blank=True, default=list)),
                ("context", models.JSONField(blank=True, default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "ordering": ["tenant_schema", "-created_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant_schema", "-created_at"],
                        name="support_ticket_tenant_idx",
                    ),
                    models.Index(fields=["status"], name="support_ticket_status_idx"),
                ],
            },
        ),
        migrations.CreateModel(
            name="SupportTicketMessage",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.shared.tenants.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "author_kind",
                    models.CharField(
                        choices=[("staff", "Staff"), ("super_admin", "Super admin")],
                        max_length=12,
                    ),
                ),
                ("author_id", models.CharField(blank=True, default="", max_length=12)),
                (
                    "author_name",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("body", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="support.supportticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
    ]
