# Generated by Django 5.2.16 on 2026-07-22 10:44

import apps.shared.tenants.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("support", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="supportticket",
            name="id",
            field=models.CharField(
                default=apps.shared.tenants.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="supportticketmessage",
            name="id",
            field=models.CharField(
                default=apps.shared.tenants.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
