# Generated by Django 5.2.16 on 2026-07-10 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="absence",
            options={"ordering": ["year", "week", "day"]},
        ),
        migrations.AlterModelOptions(
            name="absencecategory",
            options={
                "ordering": ["year", "name"],
                "verbose_name_plural": "absence categories",
            },
        ),
        migrations.AlterModelOptions(
            name="employee",
            options={"ordering": ["short_name_for_weekly_plan"]},
        ),
        migrations.AlterModelOptions(
            name="employment",
            options={"ordering": ["-valid_from"]},
        ),
        migrations.AlterModelOptions(
            name="weeklyplan",
            options={"ordering": ["year", "week", "day", "row_index"]},
        ),
        migrations.AlterModelOptions(
            name="weeklyplancategory",
            options={
                "ordering": ["name"],
                "verbose_name_plural": "weekly plan categories",
            },
        ),
        migrations.AddConstraint(
            model_name="absence",
            constraint=models.UniqueConstraint(
                fields=("year", "week", "day", "employee"),
                name="absence_one_per_employee_per_day",
            ),
        ),
        migrations.AddConstraint(
            model_name="weeklyplan",
            constraint=models.UniqueConstraint(
                fields=("year", "week", "day", "weekly_plan_category", "row_index"),
                name="weeklyplan_one_employee_per_cell",
                nulls_distinct=False,
            ),
        ),
    ]
