# Generated by Django 5.2.16 on 2026-07-21 20:02

import apps.staff.models.basics
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="absence",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="absencecategory",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="employee",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="employment",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyplan",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="weeklyplancategory",
            name="id",
            field=models.CharField(
                default=apps.staff.models.basics.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
