# Generated by Django 5.2.16 on 2026-07-14 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_absence_options_alter_absencecategory_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="weeklyplancategory",
            options={
                "ordering": ["sort_order", "name"],
                "verbose_name_plural": "weekly plan categories",
            },
        ),
        migrations.AddField(
            model_name="weeklyplancategory",
            name="sort_order",
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
