# Generated by Django 5.2.16 on 2026-07-22 12:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0002_alter_absence_id_alter_absencecategory_id_and_more"),
        ("staff", "0003_alter_weeklyplancategory_options_and_more"),
    ]

    operations = []
