# Generated by Django 5.2.15 on 2026-07-03 21:33

import apps.commissioning.models.base
import apps.shared.iban_validator
import django.db.models.deletion
import encrypted_model_fields.fields
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("commissioning", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BillingRun",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.commissioning.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "period_start",
                    models.DateField(
                        help_text="Charges with due_date in [period_start, period_end] are eligible."
                    ),
                ),
                ("period_end", models.DateField()),
                (
                    "collection_date",
                    models.DateField(
                        help_text="Requested execution date sent to the bank (RequestedCollectionDate)."
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("SEPA_DD", "SEPA Direct Debit"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="SEPA_DD",
                        max_length=20,
                    ),
                ),
                (
                    "sepa_xml_export",
                    models.FileField(blank=True, null=True, upload_to="billing_runs/"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("EXPORTED", "Exported"),
                            ("SETTLED", "Settled"),
                        ],
                        db_index=True,
                        default="DRAFT",
                        max_length=10,
                    ),
                ),
                (
                    "total_amount",
                    models.DecimalField(
                        decimal_places=2, default=Decimal("0.00"), max_digits=12
                    ),
                ),
                ("charge_count", models.PositiveIntegerField(default=0)),
                ("msg_id", models.CharField(blank=True, default="", max_length=35)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ChargeSchedule",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.commissioning.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                ("period_start", models.DateField(db_index=True)),
                ("period_end", models.DateField()),
                ("due_date", models.DateField(db_index=True)),
                (
                    "expected_amount",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("currency", models.CharField(default="EUR", max_length=3)),
                (
                    "description",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="Appears as Verwendungszweck on the bank statement.",
                        max_length=140,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PLANNED", "Planned"),
                            ("ISSUED", "Issued"),
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partially paid"),
                            ("FAILED", "Returned by bank"),
                            ("WAIVED", "Waived"),
                        ],
                        db_index=True,
                        default="PLANNED",
                        max_length=10,
                    ),
                ),
                (
                    "end_to_end_id",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="SEPA EndToEndId; used to match incoming statement lines.",
                        max_length=35,
                    ),
                ),
                (
                    "billing_run",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="charges",
                        to="payments.billingrun",
                    ),
                ),
                (
                    "member",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_schedules",
                        to="commissioning.member",
                    ),
                ),
                (
                    "subscription",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="charge_schedules",
                        to="commissioning.subscription",
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="BillingProfile",
            fields=[
                (
                    "id",
                    models.CharField(
                        default=apps.commissioning.models.base.generate_jasmin_id,
                        editable=False,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("SEPA_DD", "SEPA Direct Debit"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                        ],
                        default="SEPA_DD",
                        max_length=20,
                    ),
                ),
                (
                    "iban",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True,
                        default="",
                        validators=[apps.shared.iban_validator.IBANValidator()],
                    ),
                ),
                (
                    "account_holder",
                    encrypted_model_fields.fields.EncryptedCharField(
                        blank=True, default=""
                    ),
                ),
                (
                    "sepa_mandate_reference",
                    models.CharField(blank=True, max_length=35, null=True, unique=True),
                ),
                ("sepa_mandate_signed_at", models.DateField(blank=True, null=True)),
                (
                    "sepa_mandate_first_use_at",
                    models.DateField(
                        blank=True,
                        help_text="Set when first SEPA debit is exported. Drives FRST→RCUR.",
                        null=True,
                    ),
                ),
                (
                    "sepa_mandate_paper_received_at",
                    models.DateField(blank=True, null=True),
                ),
                ("is_active", models.BooleanField(db_index=True, default=True)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "member",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="billing_profile",
                        to="commissioning.member",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("sepa_mandate_first_use_at__isnull", True),
                            ("sepa_mandate_signed_at__isnull", True),
                            (
                                "sepa_mandate_first_use_at__gte",
                                models.F("sepa_mandate_signed_at"),
                            ),
                            _connector="OR",
                        ),
                        name="billingprofile_first_use_after_signed",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="billingrun",
            index=models.Index(
                fields=["status", "collection_date"],
                name="payments_bi_status_408fc2_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="billingrun_period_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="billingrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("collection_date__isnull", True),
                    ("period_start__isnull", True),
                    ("collection_date__gte", models.F("period_start")),
                    _connector="OR",
                ),
                name="billingrun_collection_after_period_start",
            ),
        ),
        migrations.AddIndex(
            model_name="chargeschedule",
            index=models.Index(
                fields=["member", "due_date"], name="payments_ch_member__34a4dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="chargeschedule",
            index=models.Index(
                fields=["status", "due_date"], name="payments_ch_status_5dcb98_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeschedule",
            constraint=models.UniqueConstraint(
                fields=("subscription", "period_start"),
                name="chargeschedule_unique_subscription_period",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(("period_end__gte", models.F("period_start"))),
                name="chargeschedule_period_end_gte_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="chargeschedule",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__gte", models.F("period_start")),
                    ("due_date__lte", models.F("period_end")),
                ),
                name="chargeschedule_due_date_within_period",
            ),
        ),
    ]
