# Generated by Django 5.2.16 on 2026-07-21 20:02

import apps.payments.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payments", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="billingprofile",
            name="id",
            field=models.CharField(
                default=apps.payments.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="billingrun",
            name="id",
            field=models.CharField(
                default=apps.payments.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="chargeschedule",
            name="id",
            field=models.CharField(
                default=apps.payments.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
