#!/usr/bin/env bash
# =============================================================================
# refresh_bunny_edge_ips.sh — regenerate nginx/bunny_edge_ips.conf from
# Bunny's published edge-server lists.
#
# The gateway's real_ip config trusts X-Forwarded-For ONLY when the TCP peer
# is a Bunny edge (see nginx.conf.template). This script maintains that trust
# list. Run it from the repo root; on the prod host it also live-reloads the
# gateway when the list changed.
#
#   ./scripts/refresh_bunny_edge_ips.sh              # refresh + reload if prod
#   ./scripts/refresh_bunny_edge_ips.sh --no-reload  # refresh file only
#
# Safety properties:
#   * every entry is validated as a literal IPv4/IPv6 address (python3
#     ``ipaddress``) — a compromised/HTML/error response cannot inject
#     nginx directives or bogus trust entries
#   * a fetch returning suspiciously few addresses aborts — the existing
#     file stays untouched
#   * the target file is overwritten IN PLACE (``cat > file``) so the
#     single-file bind mount into the gateway keeps its inode and a plain
#     ``nginx -s reload`` picks the change up
#
# Maintenance cadence: Bunny's fleet changes occasionally. Refresh monthly
# (calendar reminder) or before/after Bunny-related work. A stale list is
# fail-SAFE: unknown edges are simply untrusted, so their traffic logs the
# edge IP instead of the client IP — never a spoofing risk.
# =============================================================================
set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$REPO_ROOT"
TARGET="nginx/bunny_edge_ips.conf"
MIN_V4=100   # abort if Bunny "publishes" fewer than this — smells like an outage
MIN_V6=20    # same shrink guard for IPv6 (a healthy fetch is ~365)

RELOAD=1
[ "${1:-}" = "--no-reload" ] && RELOAD=0

command -v python3 >/dev/null || { echo "❌ python3 required" >&2; exit 1; }

fetch_and_validate() {
    # $1 = URL; prints one validated, NORMALIZED address per line, exits
    # non-zero on junk. Hardening (adversarial review): reject non-string JSON
    # elements — ``ipaddress.ip_address(3232235521)`` accepts a bare INT and
    # ``print(a)`` would emit ``set_real_ip_from 3232235521;`` (invalid nginx).
    # Emit ``str(ip_address(a))`` (canonical form) and skip the unspecified /
    # loopback / 0.0.0.0 addresses that must never become trusted proxies.
    curl -fsS --max-time 30 "$1" | python3 -c '
import ipaddress, json, sys
addrs = json.load(sys.stdin)
if not isinstance(addrs, list):
    sys.exit("not a JSON list")
for a in addrs:
    if not isinstance(a, str):
        sys.exit("non-string element in edge list: %r" % (a,))
    ip = ipaddress.ip_address(a)          # raises on CIDR / ranges / junk
    if ip.is_unspecified or ip.is_loopback or ip.is_multicast:
        sys.exit("refusing dangerous edge entry: %s" % a)
    print(str(ip))
'
}

echo "Fetching Bunny edge lists ..."
V4="$(fetch_and_validate https://api.bunny.net/system/edgeserverlist)"
V6="$(fetch_and_validate https://api.bunny.net/system/edgeserverlist/ipv6)"

N4="$(printf '%s\n' "$V4" | sed '/^$/d' | wc -l | tr -d ' ')"
N6="$(printf '%s\n' "$V6" | sed '/^$/d' | wc -l | tr -d ' ')"
if [ "$N4" -lt "$MIN_V4" ]; then
    echo "❌ only ${N4} IPv4 edges returned (< ${MIN_V4}) — refusing to shrink the trust list; ${TARGET} left untouched" >&2
    exit 1
fi
if [ "$N6" -lt "$MIN_V6" ]; then
    echo "❌ only ${N6} IPv6 edges returned (< ${MIN_V6}) — refusing to shrink the trust list; ${TARGET} left untouched" >&2
    exit 1
fi

STAMP="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
NEW_CONTENT="$( {
    echo "# Generated by scripts/refresh_bunny_edge_ips.sh — DO NOT EDIT BY HAND."
    echo "# ${N4} IPv4 + ${N6} IPv6 Bunny edge servers, fetched ${STAMP}."
    echo "# Trusted for real_ip client resolution (see nginx.conf.template)."
    printf '%s\n' "$V4" | sed '/^$/d; s/.*/set_real_ip_from &;/'
    printf '%s\n' "$V6" | sed '/^$/d; s/.*/set_real_ip_from &;/'
} )"

# Compare address payloads (not the timestamp header) to detect no-ops.
OLD_PAYLOAD="$(grep '^set_real_ip_from' "$TARGET" 2>/dev/null || true)"
NEW_PAYLOAD="$(printf '%s\n' "$NEW_CONTENT" | grep '^set_real_ip_from')"
if [ "$OLD_PAYLOAD" = "$NEW_PAYLOAD" ]; then
    echo "✅ ${TARGET} already current (${N4} v4 + ${N6} v6 edges) — nothing to do"
    exit 0
fi

# In-place overwrite: preserves the inode for the gateway's single-file bind
# mount, so ``nginx -s reload`` (not a restart) is enough to pick it up.
printf '%s\n' "$NEW_CONTENT" > "$TARGET"
echo "✅ wrote ${TARGET}: ${N4} IPv4 + ${N6} IPv6 edges"

if [ "$RELOAD" -eq 1 ] && command -v docker >/dev/null 2>&1 \
   && [ -n "$(docker compose ps -q gateway 2>/dev/null)" ]; then
    echo "Validating + reloading gateway ..."
    docker compose exec gateway nginx -t
    docker compose exec gateway nginx -s reload
    echo "✅ gateway reloaded with the fresh edge list"
else
    echo "(gateway not running here — commit the file; deploy/update picks it up)"
fi
