# Generated by Django 5.2.15 on 2026-07-03 21:33

import apps.accounts.models
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="JasminUser",
            fields=[
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "id",
                    models.CharField(
                        default=apps.accounts.models.generate_jasmin_id,
                        max_length=12,
                        primary_key=True,
                        serialize=False,
                        unique=True,
                        verbose_name="ID",
                    ),
                ),
                (
                    "public_id",
                    models.UUIDField(
                        db_index=True, default=uuid.uuid4, editable=False, unique=True
                    ),
                ),
                (
                    "username",
                    models.CharField(db_index=True, max_length=255, unique=True),
                ),
                ("first_name", models.CharField(max_length=255)),
                ("last_name", models.CharField(max_length=255)),
                (
                    "email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                (
                    "avatar",
                    models.ImageField(blank=True, null=True, upload_to="avatars/"),
                ),
                (
                    "account_status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("pending_approval", "Pending Admin Approval"),
                            ("pending_invitation", "Pending Invitation"),
                            ("inactive", "Inactive"),
                        ],
                        default="pending_invitation",
                        max_length=20,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                (
                    "user_language",
                    models.CharField(
                        choices=[("en", "English"), ("de", "German")],
                        default="en",
                        max_length=3,
                    ),
                ),
                ("sidebar_collapsed", models.BooleanField(default=False)),
                (
                    "theme",
                    models.CharField(
                        choices=[("light", "Light"), ("dark", "Dark")],
                        default="light",
                        help_text="User preferred theme",
                        max_length=10,
                    ),
                ),
                (
                    "edit_mode",
                    models.CharField(
                        choices=[
                            ("inline", "Inline Editing"),
                            ("modal", "Modal Editing"),
                        ],
                        default="inline",
                        help_text="User preferred editing mode",
                        max_length=10,
                    ),
                ),
                (
                    "roles",
                    models.JSONField(
                        blank=True,
                        default=list,
                        help_text="List of roles this user has",
                        null=True,
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_login_ip", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "sessions_revoked_at",
                    models.DateTimeField(blank=True, editable=False, null=True),
                ),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("inactivated_at", models.DateTimeField(blank=True, null=True)),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["public_id"], name="accounts_ja_public__0721b8_idx"
                    ),
                    models.Index(fields=["email"], name="accounts_ja_email_e706c6_idx"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            ("activated_at__isnull", True),
                            ("date_joined__isnull", True),
                            ("activated_at__gte", models.F("date_joined")),
                            _connector="OR",
                        ),
                        name="jasminuser_activated_after_joined",
                    )
                ],
            },
        ),
    ]
