# Generated by Django 5.2.15 on 2026-07-05 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jasminuser",
            name="edit_mode",
            field=models.CharField(
                choices=[("inline", "Inline Editing"), ("modal", "Modal Editing")],
                default="inline",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="jasminuser",
            name="theme",
            field=models.CharField(
                choices=[("light", "Light"), ("dark", "Dark")],
                default="light",
                max_length=10,
            ),
        ),
    ]
