# Generated by Django 5.2.16 on 2026-07-21 20:02

import apps.accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_alter_jasminuser_edit_mode_alter_jasminuser_theme"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jasminuser",
            name="id",
            field=models.CharField(
                default=apps.accounts.models.generate_jasmin_id,
                editable=False,
                max_length=12,
                primary_key=True,
                serialize=False,
                unique=True,
                verbose_name="ID",
            ),
        ),
    ]
