# Generated by Django 5.2.15 on 2026-07-12 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_jasminuser_edit_mode_alter_jasminuser_theme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jasminuser',
            name='user_language',
            field=models.CharField(choices=[('en', 'English'), ('de', 'German'), ('fr', 'French'), ('it', 'Italian')], default='en', max_length=3),
        ),
    ]
