"""drf-spectacular postprocessing hooks.

Injects the canonical ``ErrorResponseSerializer`` shape (defined in
``core.serializers``) into every operation's ``responses`` dict for the
HTTP error codes that operation can realistically produce. This avoids
having to litter every viewset with explicit ``responses={400: ...,
401: ..., ...}`` declarations:

* **401** — added to every operation. The platform's default permission
  class is ``IsAuthenticated``; the few ``AllowAny`` endpoints
  (``/login/``, ``/register/``, ``/password-reset/*``, etc.) already
  declare their own response codes and the hook's ``setdefault`` won't
  overwrite them.
* **400** — added when the operation accepts a request body
  (``requestBody`` present in the schema). Mutations with no body
  (logout, refresh, idempotent regenerate, no-body admin actions,
  ``DELETE``…) have no validation surface to 400 on, so the rule
  doesn't apply.
* **403** — added to every mutation (POST/PATCH/PUT/DELETE). The codebase
  almost universally pairs writes with role-based permissions
  (``IsOffice`` / ``IsStaff`` / ``IsAdmin``), so a 403 is reachable.
* **404** — added when the URL has a path parameter (e.g.
  ``{id}``). DRF's ``get_object`` raises ``Http404`` for unknown ids,
  surfaced as 404 by ``core.exception_handler``.

Explicit declarations on individual ``@extend_schema`` decorators ALWAYS
win — the hook uses ``setdefault`` so it never clobbers a code the view
has already documented. Use explicit declarations when you need
non-canonical codes (``409`` for state conflicts, ``500`` for backup
script failures, ``504`` for timeouts, …).

Registered in ``config.settings.SPECTACULAR_SETTINGS.POSTPROCESSING_HOOKS``.
The lock-down test lives in
``apps/shared/tests/test_openapi_schema.py``.
"""

from __future__ import annotations

from typing import Any

# Reference to ``components/schemas/ErrorResponse`` — generated by
# drf-spectacular from ``core.serializers.ErrorResponseSerializer``
# whenever any view also declares it explicitly. We add an explicit
# reference here too so the schema is registered even if no view
# declares it manually.
_ERROR_RESPONSE_REF = {
    "content": {
        "application/json": {
            "schema": {"$ref": "#/components/schemas/ErrorResponse"},
        }
    },
    "description": "Error response.",
}


_MUTATION_METHODS = {"post", "put", "patch", "delete"}


def inject_canonical_error_responses(
    result: dict[str, Any],
    generator: Any,
    request: Any,
    public: bool,
) -> dict[str, Any]:
    """Add canonical 4xx error responses to every operation.

    Per-rule details are in the module docstring. Explicit declarations
    on a view (``@extend_schema(responses={...})``) take precedence —
    ``setdefault`` won't overwrite a code already present.
    """
    paths = result.get("paths") or {}
    for path, methods in paths.items():
        if not isinstance(methods, dict):
            continue
        path_has_param = "{" in path
        for method, op in methods.items():
            if not isinstance(op, dict):
                continue
            method_lower = method.lower()
            # Skip the OpenAPI bookkeeping keys (``parameters`` etc. at
            # the path level) — only HTTP-method keys carry operations.
            if method_lower not in {
                "get",
                "post",
                "put",
                "patch",
                "delete",
                "head",
                "options",
            }:
                continue
            responses = op.setdefault("responses", {})

            # 401 — every endpoint defaults to IsAuthenticated.
            responses.setdefault("401", _ERROR_RESPONSE_REF)

            # 400 — only for operations that accept a body. If you can't
            # send bad input, you can't 400.
            if op.get("requestBody"):
                responses.setdefault("400", _ERROR_RESPONSE_REF)

            # 403 — mutations almost always carry a role check.
            if method_lower in _MUTATION_METHODS:
                responses.setdefault("403", _ERROR_RESPONSE_REF)

            # 404 — endpoints with a path parameter ({id}, {pk}, {slug},
            # {token}, ...) can hit ``DoesNotExist``.
            if path_has_param:
                responses.setdefault("404", _ERROR_RESPONSE_REF)

    # Ensure the ``ErrorResponse`` schema is registered in components
    # even if no view declared it explicitly (the $refs above would
    # otherwise dangle). drf-spectacular registers serializers under
    # their class name minus the ``Serializer`` suffix.
    components = result.setdefault("components", {})
    schemas = components.setdefault("schemas", {})
    schemas.setdefault(
        "ErrorResponse",
        {
            "type": "object",
            "properties": {
                "code": {"type": "string"},
                "message": {"type": "string"},
                "field": {"type": "string", "nullable": True},
                "details": {
                    "type": "object",
                    "additionalProperties": True,
                },
                "request_id": {"type": "string"},
            },
            "required": ["code", "message"],
        },
    )
    return result
